"""Regenerate the fixture vault's PDFs.

The PDFs under `tests/fixtures/vault/**/Files/` are committed, because the
document read path has to be tested against real bytes rather than a mock. A
committed binary nobody can read is a liability, so this is how they were made
and how to change them: edit PAGES below and run

    python tests/fixtures/make_fixture_pdfs.py

Deliberately hand-built rather than written with a PDF library. Phase 2 adds
PyMuPDF, and a fixture generated by the same library the extractor uses would
prove the extractor agrees with itself. These are uncompressed, single-font,
minimal-syntax files: a text layer and nothing else.

`has_text_layer` needs a negative case too, so one file is written with no text
operators at all - the stand-in for the scanned bill a utility provider sends.
"""

from __future__ import annotations

from pathlib import Path

VAULT = Path(__file__).parent / "vault"

# path relative to the fixture vault -> (title, lines). An empty line list makes
# a page with no text layer at all.
PAGES: dict[str, tuple[str, list[str]]] = {
    "Home/Utilities/Files/2026-09-17 Kestrel Energy - Contract Confirmation.pdf": (
        "Kestrel Energy - Contract Confirmation",
        [
            "KESTREL ENERGY LIMITED",
            "Contract confirmation",
            "",
            "Account number: KE-8842071",
            "Supply address: 14 Ashcroft Lane",
            "MPAN: 1900012345678",
            "",
            "Tariff: Kestrel Fixed 24",
            "Unit rate: 21.94p per kWh",
            "Standing charge: 41.12p per day",
            "Supply start date: 19 September 2026",
            "Fixed until: 19 September 2028",
            "Exit fee: 75.00 per fuel",
            "",
            "Your cooling off period ends 01 October 2026.",
        ],
    ),
    "Personal/Aidan/Career/Files/2026-04-02 Acme Ltd - Offer Letter.pdf": (
        "Acme Ltd - Offer Letter",
        [
            "ACME LIMITED",
            "Offer of employment",
            "",
            "Position: Automation engineer",
            "Start date: 04 May 2026",
            "Salary: 58,000 per annum",
            "Notice period: 3 months after probation",
            "Probation: 6 months",
            "",
            "This offer is subject to references.",
        ],
    ),
    # No text operators: the scanned-bill case, where extraction must report
    # thin rather than return an empty string as though it succeeded.
    "Home/Utilities/Files/2026-08-06 Brightvale Power - Tariff Change Notice.pdf": (
        "Brightvale Power - Tariff Change Notice (scan, no text layer)",
        [],
    ),
}


def _content_stream(lines: list[str]) -> bytes:
    if not lines:
        # A stroked rectangle, so the page is not empty of *marks* - just of
        # text. An extractor that reports "no pages" rather than "no text layer"
        # on this file is answering the wrong question.
        return b"0.5 w 72 72 451 698 re S\n"

    out = [b"BT\n/F1 11 Tf\n14 TL\n72 760 Td\n"]
    for line in lines:
        escaped = (
            line.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
        ).encode("latin-1")
        out.append(b"(" + escaped + b") Tj\nT*\n")
    out.append(b"ET\n")
    return b"".join(out)


def build_pdf(title: str, lines: list[str]) -> bytes:
    stream = _content_stream(lines)

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"endstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
        b"<< /Title (" + title.encode("latin-1") + b") /Producer (vault-mcp fixture) >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets: list[int] = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{number} 0 obj\n".encode() + body + b"\nendobj\n"

    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R /Info 6 0 R >>\n"
        f"startxref\n{xref_at}\n"
    ).encode()
    out += b"%%EOF\n"
    return bytes(out)


def main() -> None:
    for rel, (title, lines) in PAGES.items():
        target = VAULT / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(build_pdf(title, lines))
        kind = "no text layer" if not lines else f"{len(lines)} lines"
        print(f"wrote {rel} ({target.stat().st_size} bytes, {kind})")


if __name__ == "__main__":
    main()
